import type { KeyboardLayout } from './types'

/**
 * Windows "Arabic (101)", identical to macOS "Arabic – PC" and the default Linux/ChromeOS Arabic
 * layout. The lam-alef key types two characters, so `ل`+`ا` from `g`+`h` reads back as `b`.
 */
export const AR_PC = Object.freeze<KeyboardLayout>({
  id: 'ar-pc',
  language: 'ar',
  label: 'العربية (PC)',
  chip: 'ع',
  script: 'Arab',
  platform: 'pc',
  keys: {
    Backquote: ['ذ', '\u0651'],
    KeyQ: ['ض', '\u064E'],
    KeyW: ['ص', '\u064B'],
    KeyE: ['ث', '\u064F'],
    KeyR: ['ق', '\u064C'],
    KeyT: ['ف', 'لإ'],
    KeyY: ['غ', 'إ'],
    KeyU: ['ع', '‘'],
    KeyI: ['ه', '÷'],
    KeyO: ['خ', '×'],
    KeyP: ['ح', '؛'],
    BracketLeft: ['ج', '<'],
    BracketRight: ['د', '>'],
    KeyA: ['ش', '\u0650'],
    KeyS: ['س', '\u064D'],
    KeyD: ['ي', ']'],
    KeyF: ['ب', '['],
    KeyG: ['ل', 'لأ'],
    KeyH: ['ا', 'أ'],
    KeyJ: ['ت', 'ـ'],
    KeyK: ['ن', '،'],
    KeyL: ['م', '/'],
    Semicolon: ['ك', null],
    Quote: ['ط', null],
    KeyZ: ['ئ', '~'],
    KeyX: ['ء', '\u0652'],
    KeyC: ['ؤ', '}'],
    KeyV: ['ر', '{'],
    KeyB: ['لا', 'لآ'],
    KeyN: ['ى', 'آ'],
    KeyM: ['ة', '’'],
    Comma: ['و', ','],
    Period: ['ز', '.'],
    Slash: ['ظ', '؟'],
  },
  aliases: {
    '٠': 'Digit0',
    '١': 'Digit1',
    '٢': 'Digit2',
    '٣': 'Digit3',
    '٤': 'Digit4',
    '٥': 'Digit5',
    '٦': 'Digit6',
    '٧': 'Digit7',
    '٨': 'Digit8',
    '٩': 'Digit9',
  },
})
