import type { KeyboardLayout } from './types'

/** macOS default "Arabic": several letters sit on different keys than the PC layout, and there is no lam-alef key. */
export const AR_MAC = Object.freeze<KeyboardLayout>({
  id: 'ar-mac',
  language: 'ar',
  label: 'العربية (Mac)',
  chip: 'ع',
  script: 'Arab',
  platform: 'mac',
  keys: {
    Backquote: ['ـ', null],
    KeyQ: ['ض', '\u064E'],
    KeyW: ['ص', '\u064B'],
    KeyE: ['ث', '\u0650'],
    KeyR: ['ق', '\u064D'],
    KeyT: ['ف', '\u064F'],
    KeyY: ['غ', '\u064C'],
    KeyU: ['ع', '\u0652'],
    KeyI: ['ه', '\u0651'],
    KeyO: ['خ', ']'],
    KeyP: ['ح', '['],
    BracketLeft: ['ج', null],
    BracketRight: ['ة', null],
    KeyA: ['ش', '»'],
    KeyS: ['س', '«'],
    KeyD: ['ي', 'ى'],
    KeyF: ['ب', null],
    KeyG: ['ل', null],
    KeyH: ['ا', 'آ'],
    KeyJ: ['ت', null],
    KeyK: ['ن', '٫'],
    KeyL: ['م', '٬'],
    Semicolon: ['ك', null],
    Quote: ['؛', null],
    KeyZ: ['ظ', "'"],
    KeyX: ['ط', null],
    KeyC: ['ذ', 'ئ'],
    KeyV: ['د', 'ء'],
    KeyB: ['ز', 'أ'],
    KeyN: ['ر', 'إ'],
    KeyM: ['و', 'ؤ'],
    Comma: ['،', null],
    Slash: [null, '؟'],
  },
  aliases: {
    '٠': 'Digit0',
    '١': 'Digit1',
    '٢': 'Digit2',
    '٣': 'Digit3',
    '٤': 'Digit4',
    '٥': 'Digit5',
    '٦': 'Digit6',
    '٧': 'Digit7',
    '٨': 'Digit8',
    '٩': 'Digit9',
  },
})
