use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2_app_kit::{NSPasteboard, NSPasteboardItem, NSPasteboardTypeString, NSPasteboardWriting};
use objc2_foundation::{NSArray, NSData, NSString};

use crate::fix::{Clipboard, FixError, Representation, Snapshot};

/// nspasteboard.org conventions: clipboard managers skip items carrying these types.
const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

pub struct MacClipboard;

fn general() -> Retained<NSPasteboard> {
    NSPasteboard::generalPasteboard()
}

fn write_items(items: &[Retained<NSPasteboardItem>]) -> Result<(), FixError> {
    let pasteboard = general();
    pasteboard.clearContents();
    if items.is_empty() {
        return Ok(());
    }
    let writers: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> = items
        .iter()
        .map(|item| ProtocolObject::from_retained(item.clone()))
        .collect();
    if pasteboard.writeObjects(&NSArray::from_retained_slice(&writers)) {
        Ok(())
    } else {
        Err(FixError::System("NSPasteboard refused the items".into()))
    }
}

fn item_with(representations: &[(&str, &[u8])]) -> Retained<NSPasteboardItem> {
    let item = NSPasteboardItem::new();
    for (kind, data) in representations {
        item.setData_forType(&NSData::with_bytes(data), &NSString::from_str(kind));
    }
    item
}

impl Clipboard for MacClipboard {
    fn change_count(&self) -> i64 {
        general().changeCount() as i64
    }

    fn read_text(&self) -> Option<String> {
        // SAFETY: NSPasteboardTypeString is an immutable AppKit constant.
        let kind = unsafe { NSPasteboardTypeString };
        general().stringForType(kind).map(|text| text.to_string())
    }

    fn snapshot(&self) -> Snapshot {
        let Some(items) = general().pasteboardItems() else {
            return Snapshot::default();
        };
        let items = items
            .iter()
            .map(|item| {
                item.types()
                    .iter()
                    .filter_map(|kind| {
                        item.dataForType(&kind).map(|data| Representation {
                            kind: kind.to_string(),
                            data: data.to_vec(),
                        })
                    })
                    .collect()
            })
            .collect();
        Snapshot { items }
    }

    fn restore(&self, snapshot: &Snapshot) -> Result<(), FixError> {
        let items: Vec<_> = snapshot
            .items
            .iter()
            .map(|reps| {
                let pairs: Vec<(&str, &[u8])> = reps
                    .iter()
                    .map(|rep| (rep.kind.as_str(), rep.data.as_slice()))
                    .collect();
                item_with(&pairs)
            })
            .collect();
        write_items(&items)
    }

    fn write_transient_text(&self, text: &str) -> Result<(), FixError> {
        // SAFETY: NSPasteboardTypeString is an immutable AppKit constant.
        let string_type = unsafe { NSPasteboardTypeString }.to_string();
        let item = item_with(&[
            (string_type.as_str(), text.as_bytes()),
            (TRANSIENT_TYPE, b""),
            (AUTO_GENERATED_TYPE, b""),
        ]);
        write_items(&[item])
    }
}
